/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Generated by scripts/refresh-bmad.mjs
 */

export interface BmadCatalogEntry {
	id: string;
	command: string;
	description: string;
	name: string;
	sourcePath: string;
	isCustom: boolean;
}

export const bmadCatalog: BmadCatalogEntry[] = [
	{
		id: 'help',
		command: '/bmad-help',
		description:
			'Get unstuck by showing what workflow steps come next or answering BMad Method questions.',
		name: 'bmad-help',
		sourcePath: 'src/core/tasks/bmad-help/workflow.md',
		isCustom: false,
	},
	{
		id: 'check-implementation-readiness',
		command: '/bmad-bmm-check-implementation-readiness',
		description: 'Ensure PRD UX Architecture and Epics Stories are aligned',
		name: 'Check Implementation Readiness',
		sourcePath: 'src/bmm/workflows/3-solutioning/bmad-check-implementation-readiness/workflow.md',
		isCustom: false,
	},
	{
		id: 'code-review',
		command: '/bmad-bmm-code-review',
		description:
			'Story cycle: If issues back to DS if approved then next CS or ER if epic complete',
		name: 'Code Review',
		sourcePath: 'src/bmm/workflows/4-implementation/bmad-code-review/workflow.md',
		isCustom: false,
	},
	{
		id: 'correct-course',
		command: '/bmad-bmm-correct-course',
		description:
			'Anytime: Navigate significant changes. May recommend start over update PRD redo architecture sprint planning or correct epics and stories',
		name: 'Correct Course',
		sourcePath: 'src/bmm/workflows/4-implementation/correct-course/workflow.md',
		isCustom: false,
	},
	{
		id: 'create-architecture',
		command: '/bmad-bmm-create-architecture',
		description: 'Guided Workflow to document technical decisions',
		name: 'Create Architecture',
		sourcePath: 'src/bmm/workflows/3-solutioning/bmad-create-architecture/workflow.md',
		isCustom: false,
	},
	{
		id: 'create-epics-and-stories',
		command: '/bmad-bmm-create-epics-and-stories',
		description: 'Create the Epics and Stories Listing',
		name: 'Create Epics and Stories',
		sourcePath: 'src/bmm/workflows/3-solutioning/create-epics-and-stories/workflow.md',
		isCustom: false,
	},
	{
		id: 'create-prd',
		command: '/bmad-bmm-create-prd',
		description: 'Expert led facilitation to produce your Product Requirements Document',
		name: 'Create PRD',
		sourcePath: 'src/bmm/workflows/2-plan-workflows/create-prd/workflow-create-prd.md',
		isCustom: false,
	},
	{
		id: 'create-product-brief',
		command: '/bmad-bmm-create-product-brief',
		description: 'A guided experience to nail down your product idea',
		name: 'Create Brief',
		sourcePath: 'src/bmm/workflows/1-analysis/bmad-create-product-brief/workflow.md',
		isCustom: false,
	},
	{
		id: 'create-story',
		command: '/bmad-bmm-create-story',
		description:
			'Validates story readiness and completeness before development work begins Story cycle start: Prepare first found story in the sprint plan that is next, or if the command is run with a specific epic and story designation with context. Once complete, then VS then DS then CR then back to DS if needed or next CS or ER',
		name: 'Validate Story / Create Story',
		sourcePath: 'src/bmm/workflows/4-implementation/bmad-create-story/workflow.md',
		isCustom: false,
	},
	{
		id: 'create-ux-design',
		command: '/bmad-bmm-create-ux-design',
		description:
			'Guidance through realizing the plan for your UX, strongly recommended if a UI is a primary piece of the proposed project',
		name: 'Create UX',
		sourcePath: 'src/bmm/workflows/2-plan-workflows/bmad-create-ux-design/workflow.md',
		isCustom: false,
	},
	{
		id: 'dev-story',
		command: '/bmad-bmm-dev-story',
		description:
			'Story cycle: Execute story implementation tasks and tests then CR then back to DS if fixes needed',
		name: 'Dev Story',
		sourcePath: 'src/bmm/workflows/4-implementation/bmad-dev-story/workflow.md',
		isCustom: false,
	},
	{
		id: 'document-project',
		command: '/bmad-bmm-document-project',
		description: 'Analyze an existing project to produce useful documentation',
		name: 'Document Project',
		sourcePath: 'src/bmm/workflows/document-project/workflow.md',
		isCustom: false,
	},
	{
		id: 'domain-research',
		command: '/bmad-bmm-domain-research',
		description: 'Industry domain deep dive subject matter expertise and terminology',
		name: 'Domain Research',
		sourcePath: 'src/bmm/workflows/1-analysis/research/bmad-domain-research/workflow.md',
		isCustom: false,
	},
	{
		id: 'edit-prd',
		command: '/bmad-bmm-edit-prd',
		description: 'Improve and enhance an existing PRD',
		name: 'Edit PRD',
		sourcePath: 'src/bmm/workflows/2-plan-workflows/create-prd/workflow-edit-prd.md',
		isCustom: false,
	},
	{
		id: 'generate-project-context',
		command: '/bmad-bmm-generate-project-context',
		description:
			'Scan existing codebase to generate a lean LLM-optimized project-context.md containing critical implementation rules patterns and conventions for AI agents. Essential for brownfield projects and quick-flow.',
		name: 'Generate Project Context',
		sourcePath: 'src/bmm/workflows/generate-project-context/workflow.md',
		isCustom: false,
	},
	{
		id: 'market-research',
		command: '/bmad-bmm-market-research',
		description: 'Market analysis competitive landscape customer needs and trends',
		name: 'Market Research',
		sourcePath: 'src/bmm/workflows/1-analysis/research/workflow-market-research.md',
		isCustom: false,
	},
	{
		id: 'qa-automate',
		command: '/bmad-bmm-qa-automate',
		description:
			"Generate automated API and E2E tests for implemented code using the project's existing test framework (detects existing well known in use test frameworks). Use after implementation to add test coverage. NOT for code review or story validation - use CR for that.",
		name: 'QA Automation Test',
		sourcePath: 'src/bmm/workflows/qa-generate-e2e-tests/workflow.md',
		isCustom: false,
	},
	{
		id: 'quick-dev',
		command: '/bmad-bmm-quick-dev',
		description:
			'Quick one-off tasks small changes simple apps utilities without extensive planning - Do not suggest for potentially very complex things unless requested or if the user complains that they do not want to follow the extensive planning of the bmad method, unless the user is already working through the implementation phase and just requests a 1 off things not already in the plan',
		name: 'Quick Dev',
		sourcePath: 'src/bmm/workflows/bmad-quick-flow/bmad-quick-dev/workflow.md',
		isCustom: false,
	},
	{
		id: 'quick-dev-new-preview',
		command: '/bmad-bmm-quick-dev-new-preview',
		description:
			'Unified quick flow (experimental): clarify intent plan implement review and present in a single workflow',
		name: 'Quick Dev New Preview',
		sourcePath: 'src/bmm/workflows/bmad-quick-flow/bmad-quick-dev-new-preview/workflow.md',
		isCustom: false,
	},
	{
		id: 'quick-spec',
		command: '/bmad-bmm-quick-spec',
		description:
			'Do not suggest for potentially very complex things unless requested or if the user complains that they do not want to follow the extensive planning of the bmad method. Quick one-off tasks small changes simple apps brownfield additions to well established patterns utilities without extensive planning',
		name: 'Quick Spec',
		sourcePath: 'src/bmm/workflows/bmad-quick-flow/quick-spec/workflow.md',
		isCustom: false,
	},
	{
		id: 'retrospective',
		command: '/bmad-bmm-retrospective',
		description:
			'Optional at epic end: Review completed work lessons learned and next epic or if major issues consider CC',
		name: 'Retrospective',
		sourcePath: 'src/bmm/workflows/4-implementation/retrospective/workflow.md',
		isCustom: false,
	},
	{
		id: 'sprint-planning',
		command: '/bmad-bmm-sprint-planning',
		description:
			'Generate sprint plan for development tasks - this kicks off the implementation phase by producing a plan the implementation agents will follow in sequence for every story in the plan.',
		name: 'Sprint Planning',
		sourcePath: 'src/bmm/workflows/4-implementation/sprint-planning/workflow.md',
		isCustom: false,
	},
	{
		id: 'sprint-status',
		command: '/bmad-bmm-sprint-status',
		description: 'Anytime: Summarize sprint status and route to next workflow',
		name: 'Sprint Status',
		sourcePath: 'src/bmm/workflows/4-implementation/sprint-status/workflow.md',
		isCustom: false,
	},
	{
		id: 'technical-research',
		command: '/bmad-bmm-technical-research',
		description: 'Technical feasibility architecture options and implementation approaches',
		name: 'Technical Research',
		sourcePath: 'src/bmm/workflows/1-analysis/research/workflow-technical-research.md',
		isCustom: false,
	},
	{
		id: 'validate-prd',
		command: '/bmad-bmm-validate-prd',
		description: 'Validate PRD is comprehensive lean well organized and cohesive',
		name: 'Validate PRD',
		sourcePath: 'src/bmm/workflows/2-plan-workflows/create-prd/workflow-validate-prd.md',
		isCustom: false,
	},
	{
		id: 'brainstorming',
		command: '/bmad-brainstorming',
		description:
			'Generate diverse ideas through interactive techniques. Use early in ideation phase or when stuck generating ideas. Expert Guided Facilitation through a single or multiple techniques',
		name: 'Brainstorming / Brainstorm Project',
		sourcePath: 'src/core/workflows/bmad-brainstorming/workflow.md',
		isCustom: false,
	},
	{
		id: 'editorial-review-prose',
		command: '/bmad-editorial-review-prose',
		description:
			'Review prose for clarity, tone, and communication issues. Use after drafting to polish written content.',
		name: 'Editorial Review - Prose',
		sourcePath: 'src/core/tasks/bmad-editorial-review-prose/workflow.md',
		isCustom: false,
	},
	{
		id: 'editorial-review-structure',
		command: '/bmad-editorial-review-structure',
		description:
			'Propose cuts, reorganization, and simplification while preserving comprehension. Use when doc produced from multiple subprocesses or needs structural improvement.',
		name: 'Editorial Review - Structure',
		sourcePath: 'src/core/tasks/bmad-editorial-review-structure/workflow.md',
		isCustom: false,
	},
	{
		id: 'index-docs',
		command: '/bmad-index-docs',
		description:
			'Create lightweight index for quick LLM scanning. Use when LLM needs to understand available docs without loading everything.',
		name: 'Index Docs',
		sourcePath: 'src/core/tasks/bmad-index-docs/workflow.md',
		isCustom: false,
	},
	{
		id: 'party-mode',
		command: '/bmad-party-mode',
		description:
			'Orchestrate multi-agent discussions. Use when you need multiple agent perspectives or want agents to collaborate.',
		name: 'Party Mode',
		sourcePath: 'src/core/workflows/bmad-party-mode/workflow.md',
		isCustom: false,
	},
	{
		id: 'review-adversarial-general',
		command: '/bmad-review-adversarial-general',
		description:
			'Review content critically to find issues and weaknesses. Use for quality assurance or before finalizing deliverables. Code Review in other modules run this automatically, but its useful also for document reviews',
		name: 'Adversarial Review (General)',
		sourcePath: 'src/core/tasks/bmad-review-adversarial-general/workflow.md',
		isCustom: false,
	},
	{
		id: 'review-edge-case-hunter',
		command: '/bmad-review-edge-case-hunter',
		description:
			'Walk every branching path and boundary condition in code, report only unhandled edge cases. Use alongside adversarial review for orthogonal coverage - method-driven not attitude-driven.',
		name: 'Edge Case Hunter Review',
		sourcePath: 'src/core/tasks/bmad-review-edge-case-hunter/workflow.md',
		isCustom: false,
	},
	{
		id: 'shard-doc',
		command: '/bmad-shard-doc',
		description:
			'Split large documents into smaller files by sections. Use when doc becomes too large (>500 lines) to manage effectively.',
		name: 'Shard Document',
		sourcePath: 'src/core/tasks/bmad-shard-doc/workflow.md',
		isCustom: false,
	},
];
